### ISSUE TITLE
AI milestone

### ISSUE THREAD

**Issue by quentin-sommer** [quentin-sommer/gomoku-front#2]
- [x] Ask if it's a human vs AI or human vs human game before entering room 
- [x] Show control during game to switch ai strength field in PLAY_TURN (to change depth of minmax)
- [x] Show visual move suggestion
